<template>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
    <div>switch</div>
</template>

<script>
export default {
  name: "Dialog",
};
</script>

<style lang="scss" scoped>

</style>